#INCLUDE "Protheus.ch"
#INCLUDE "RWMake.ch"
#Include "ParmType.ch"
#INCLUDE "CXInclude.ch"

#DEFINE MAX_PARAM 	60

//#############################################################################
//##+----------+-------------+-------+--------------------+------+----------+##
//##|Programa  | CXRestParam | Autor | Cirilo Rocha       | Data |21/08/2011|##
//##+----------+-------------+-------+--------------------+------+----------+##
//##|Descr.    | Restaura os parâmetros salvos pela função CXGetParam()     |##
//##+----------+-----------+------------------------------------------------+##
//##|   DATA   |Programador| Manutenção efetuada                            |##
//##+----------+-----------+------------------------------------------------+##
//##| 03/09/19 | Cirilo R. | Pequena revisão no fonte                       |##
//##| 23/02/23 | Cirilo R. | Pequena revisão no fonte                       |##
//##|          |           |                                                |##
//##|          |           |                                                |##
//##+----------+-----------+------------------------------------------------+##
//#############################################################################
User Function CXRestParam(aPar)

	//Declaracao de variaveis----------------------------------------------------------------------
	Local nX		AS Integer
	
	//Parametros da rotina-------------------------------------------------------------------------
	ParamType 0		VAR aPar			AS Array

	//---------------------------------------------------------------------------------------------
	For nX := 1 to Min(len(aPar),MAX_PARAM)
		&('MV_PAR'+StrZero(nX,2)) := aPar[nX]
	Next

Return