Static nRT_FOLHA	:= '1' // Folha de Pagamento
Static nRT_ADTO 	:= '2' // Adiantamento
Static nRT_FERIAS 	:= '3' // Ferias
Static nRT_RESCIS 	:= '4' // Rescisao
Static nRT_131 		:= '5' // 1a.Parcela 13o.Salario
Static nRT_132 		:= '6' // 2a.Parcela 13o.Salario
Static nRT_OUTROS 	:= '7' // Outros
Static nRT_VAL_TR 	:= '8' // Vale Transporte
Static nRT_AUTONO 	:= '9' // Autonomos
Static nRT_PROVIS 	:= 'A' // Provisao
