#include 'tlpp-core.th'
#include 'totvs.ch'
#include 'fwmvcdef.ch'

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} CXInvRPO
@description	Efetua o inventário dos fontes do RPO gerando um arquivo CSV com os dados
@autor			Cirilo Rocha
@since			25/04/2023
-------------------------------------------------------------------------------------------------*/
#Define _MsgLinha_		'CXInvRPO-'+StrZero(ProcLine(),5)
Static cExtPrj		:= 'PRG,PRW,PRX,TLPP'	//Extenções de arquivos válidas para o projeto
//-- Pseudo-Função para Extrair extensão do arquivo
#xTranslate _CxGetExt(<cTexto>) => ;
	Iif( (_nP:=Rat('.',<cTexto>))>0 , SubStr(<cTexto>,_nP+1) ,'')
//-- Pseudo método para adicionar atributos em objetos Json, apenas para deixar a sintaxe mais clara
#xTranslate	 :_addAtributo(<cAtributo>) => \[<cAtributo>\]
//---------------------------------------------------------------------------------------------
User Function CXInvRPO()

	//-- Declaração de Variáveis ----------------------------------------------
	Local cDescr									AS Character
	Local cDirDst									AS Character
	Local cDirPrj									AS Character
	Local nL										AS Numeric
	Local oDlg										AS Object
	Local oGrp										AS Object

	//-- Inicializa Variáveis -------------------------------------------------
	cDescr	:= 'Esta rotina tem por objeto gerar um inventário dos fontes customizados do RPO e '+;
				'pesquisá-los no diretório do projeto comparando a data e hora dos arquivos com '+;
				'o que está no RPO.'
	
	cDirDst	:= Padr('C:\Protheus\',250)
	cDirPrj	:= Space(250)
	Set(_SET_DATEFORMAT, 'mm/dd/yyyy') // Data com QUATRO digitos para Ano

	//-- Criação do Dialog ----------------------------------------------------
    oDlgModal  := FWDialogModal():New()
		oDlgModal:SetEscClose(.T.)
		oDlgModal:setTitle(_MsgLinha_+" - Geração de Invetário de Fontes")
		oDlgModal:setSize(195, 210)	//-- Altura em pixels / 1.5
		oDlgModal:createDialog()
	
		oDlg := oDlgModal:getPanelMain()

		nL	:= 000
		oGrp	:= TGroup():New(nL,004,033,205,"Destino:"  ,oDlg,,,.T.)
		TGet():New(nL+010,008,bSetGet(cDirDst),oGrp,171,010,,,,,,,,.T.)
		TBtnBmp2():New(nL+020,360,026,026,"SDUOPEN",,,,{|| sfGetDir(@cDirDst) },oGrp,"Pesquisa local de destino")

		nL	+= 040
		oGrp	:= TGroup():New(nL,004,073,205,"Diretório Projeto:"  ,oDlg,,,.T.)
		TGet():New(nL+010,008,bSetGet(cDirPrj),oGrp,171,010,,,,,,,,.T.)
		TBtnBmp2():New(nL+060,360,026,026,"SDUOPEN",,,,{|| sfGetDir(@cDirPrj) },oGrp,"Pesquisa local do projeto")

		nL	+= 040
		oGrp	:= TGroup():New(nL,004,140,205," Descrição: ",oDlg,,,.T.)
		TMultiGet():New(nL+010,008,bSetGet(cDescr),oGrp,192,040,,,,,,.T.,,,,,,.T.,,,)

		//-- Preciso acrescentar os botões aqui após o createDialog -------------------------------
		oDlgModal:addCloseButton({|| oDlgModal:DeActivate() }, 'Cancelar')
		oDlgModal:addOkButton({|| sfBuscaFontes(cDirDst,cDirPrj) ,oDlgModal:DeActivate() }, 'OK')

	oDlgModal:Activate()

	FreeObj(oDlg)

Return




//---------------------------------------------------------------------------------------------
Static Function sfGetDir( cDiretorio	AS Character )	//-- Por referência
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local cPath			AS Character
	Local nOpcoes		AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR cDiretorio		AS Character

	//-------------------------------------------------------------------------
	nOpcoes	:= GETF_LOCALFLOPPY+GETF_NETWORKDRIVE+GETF_LOCALHARD+GETF_RETDIRECTORY
	cPath 	:= cGetFile('*.*'					;	//01 cMascara
					,	"Selecione o diretório"	;	//02 cTitulo
					,	0						;	//03 nMascPadrao
					,	cDiretorio				;	//04 cDirInicial
					,	.T.						;	//05 lSalvar
					,	nOpcoes					;	//06 nOpcoes
					,	.T.						;	//07 lServer
					,	.T.						;	//08 lKeepCase
					)

	If .Not. Empty(cPath)
		cDiretorio	:= PadR(cPath,250)
	EndIf

Return




//-------------------------------------------------------------------------------------------------
Static Function sfBuscaFontes(	cDirDst	AS Character;	//01 cDirDst
							,	cDirPrj	AS Character;	//02 cDirPrj
							)

	//-- Declaração de Variáveis ----------------------------------------------
	Local cArqDst					AS Character
	Local lOK		:= .F.			AS Logical

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR cDirDst		AS Character
	ParamType 1		VAR cDirPrj		AS Character
	
	//-- Inicializa Variáveis -------------------------------------------------
	cDirDst	:= AllTrim(cDirDst)
	cDirPrj	:= AllTrim(cDirPrj)
	cArqDst	:= cDirDst+'\CXInvRPO-'+DtoS(Date())+'-'+StrTran(Time(),':',';')+'.csv'

	//---------------------------------------------------------------------------------------------
	FWMsgRun(/*oSay*/,	{|| lOK	:= sfProcRPO(cArqDst,	cDirPrj	) }	;
		,	_MsgLinha_+' - Preenchendo dados...'					;
		,	'Aguarde...'											;
		)
	
	If lOK
		FwAlertInfo('Inventário gravado com sucesso.'	;
			+CRLF+	cArqDst								;
			,_MsgLinha_)
	EndIf

Return




//-------------------------------------------------------------------------------------------------
Static Function sfProcRPO(	cArqDst	AS Character;	//01 cArqDst
						,	cDirPrj	AS Character;	//02 cDirPrj
						)							AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local aArquivos		:= {}			AS Array
	Local ajFontes		:= {}			AS Array
	Local aRPOSrc						AS Array

	Local aType			:= {}			AS Array	//-- Origem da função: FULL, USER, PARTNER, PATCH, TEMPLATE ou NONE
	Local aFile			:= {}			AS Array	//-- Nome do arquivo onde foi declarada a função
	Local aLine			:= {}			AS Array	//-- Número da linha no arquivo onde foi declarada a função
	Local aDate			:= {}			AS Array	//-- Data do código fonte compilado
	Local aTime			:= {}			AS Array	//-- Hora do código fonte compilado	

	Local cTexto						AS Character
	Local cDirDst						AS Character

	Local cDrive						AS Character
	Local cDir							AS Character
	Local cFile							AS Character
	Local cExten						AS Character

	Local lOK			:= .T.			AS Logical

	Local nPos							AS Numeric
	Local nX							AS Numeric
	Local nRPOCustom	:= 3			AS Numeric		//1 - RPO Padrão, 2 - RPO TLPP, 3 - RPO Custom

	Local oFile							AS Object

	//Posições do retorno da função Directory
	Private cDR_NOME	:= 01			AS Numeric
//	Private nDR_TAM		:= 02			AS Numeric
	Private dDR_DATA	:= 03			AS Numeric
	Private cDR_HORA	:= 04			AS Numeric
	Private cDR_TIPO	:= 05			AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR cArqDst		AS Character
	ParamType 1		VAR cDirPrj		AS Character

	//-------------------------------------------------------------------------
	If lOK
		SplitPath( cArqDst,@cDrive,@cDir, @cFile, @cExten )
		cDirDst	:= cDrive+cDir

		oFile	:= FWFileWriter():New(cArqDst,.T.)
		oFile:SetCaseSensitive(.T.) //Força respeitar case do nome do arquivo
		If .Not. ExistDir(cDirDst)
			oFile:CreateDirectory()
		EndIf
		If .Not. ExistDir(cDirDst)
			FwAlertError(	'ERRO ao criar diretório destino.'	;
					+CRLF+	'Destino: '+cDirDst					;
					,_MsgLinha_)
			lOK	:= .F.
		EndIf

		If 	lOK .And. ;
			.Not. oFile:Create()
 
			FwAlertError('ERRO ao criar arquivo de destino.'	;
				+CRLF+	'Arquivo: '+AllTrim(oFile:cFileName)	;
				+CRLF+	'Erro: '+oFile:Error():Message			;
				,_MsgLinha_)
			lOK	:= .F.
		EndIf
	EndIf

	//-- Busca os fontes do RPO -----------------------------------------------
	If lOK
		aRPOSrc := GetFuncArray('*',@aType,@aFile,@aLine,@aDate,@aTime,nRPOCustom)

		For nX := 1 to Len(aRPOSrc)
			If Upper(_CxGetExt(aFile[nX])) $ cExtPrj	//Apenas estas extensões!
				nPos	:= aScan(ajFontes,{|x| Upper(x:programa) == Upper(aFile[nX]) })
				If nPos == 0
					aAdd(ajFontes,sfGetJsonFonte())
					nPos	:= Len(ajFontes)
					ajFontes[nPos]:programa	:= aFile[nX]
					ajFontes[nPos]:prjNome	:= ''
					ajFontes[nPos]:prjData	:= Ctod('')
					ajFontes[nPos]:prjHora	:= ''
					ajFontes[nPos]:rpoNome	:= aFile[nX]
					ajFontes[nPos]:rpoData	:= aDate[nX]
					ajFontes[nPos]:rpoHora	:= aTime[nX]
				EndIf
				//NO CASO DO RPO PRECISO FAZER AQUI MESMO E APENAS ADICIONANDO, PORQUE OS FONTES VEM 
				// REPEDITOS, VISTO QUE A ROTINA RETORNA NOMES DE FUNÇÕES E NÃO DOS FONTES
			EndIf
		Next
	EndIf

	//-- Carrego a lista dos arquivos do projeto ------------------------------
	If lOK
		If .Not. Empty(cDirPrj)
			sfGetArqDir(cDirPrj		;	//01 cDir
					,	@aArquivos	;	//02 @aArquivos
					)
		EndIf
		aSort(aArquivos,/*nPIni*/,/*nQtd*/,{|x,y| x[cDR_NOME] > y[cDR_NOME] })	//Precisei forçar a ordenadação!

		For nX := 1 to Len(aArquivos)
			If Upper(_CxGetExt(aArquivos[nX][cDR_NOME])) $ cExtPrj	//Apenas estas extensões!
				SplitPath( aArquivos[nX][cDR_NOME],@cDrive,@cDir, @cFile, @cExten )
				nPos		:= aScan(ajFontes,{|x| Upper(x:programa) == Upper(cFile+cExten) })
				If nPos == 0
					aAdd(ajFontes,sfGetJsonFonte())
					nPos	:= Len(ajFontes)
					ajFontes[nPos]:programa	:= cFile+cExten
					ajFontes[nPos]:prjNome	:= ''
					ajFontes[nPos]:prjData	:= Ctod('')
					ajFontes[nPos]:prjHora	:= ''
					ajFontes[nPos]:rpoNome	:= ''
					ajFontes[nPos]:rpoData	:= Ctod('')
					ajFontes[nPos]:rpoHora	:= ''
				EndIf

				//Preencho os dados
				ajFontes[nPos]:prjNome	:= aArquivos[nX][cDR_NOME]
				ajFontes[nPos]:prjData	:= aArquivos[nX][dDR_DATA]
				ajFontes[nPos]:prjHora	:= aArquivos[nX][cDR_HORA]
			EndIf
		Next
	EndIf

	//-- Gravação do arquivo --------------------------------------------------
	If lOK
		//Cabeçalho
		If .Not. oFile:Write('Programa;Fonte Projeto;Data Projeto;Hora Projeto;Fonte RPO;Data RPO;Hora RPO;Divergente?'+CRLF)
			FwAlertError('ERRO ao gravar arquivo de destino.'	;
				+CRLF+	'Arquivo: '+AllTrim(oFile:cFileName)	;
				+CRLF+	'Erro: '+oFile:Error():Message			;
				,_MsgLinha_)
			lOK	:= .F.
		EndIf

		If lOK
			For nX := 1 to Len(ajFontes)
				cTexto	:= 	ajFontes[nX]:programa		;
					+';'+	ajFontes[nX]:prjNome		;
					+';'+	DtoC(ajFontes[nX]:prjData)	;
					+';'+	ajFontes[nX]:prjHora		;
					+';'+	ajFontes[nX]:rpoNome		;
					+';'+	DtoC(ajFontes[nX]:rpoData)	;
					+';'+	ajFontes[nX]:rpoHora		;
					+';'

				//Divergencias---------------------------------------------------
				If 		Empty(ajFontes[nX]:prjData)
					cTexto	+= '4=NÃO Existe no Projeto'
				ElseIf	Empty(ajFontes[nX]:rpoData)
					cTexto	+= '3=NÃO Existe no RPO'
				ElseIf FwSubtHora(	ajFontes[nX]:rpoData,ajFontes[nX]:rpoHora	;	//RPO
								,	ajFontes[nX]:prjData,ajFontes[nX]:prjHora	;	//Projeto
								) > 1
					cTexto	+= '2=RPO Mais ANTIGO'
				ElseIf FwSubtHora(	ajFontes[nX]:rpoData,ajFontes[nX]:rpoHora	;	//RPO
								,	ajFontes[nX]:prjData,ajFontes[nX]:prjHora	;	//Projeto
								) > 1
					cTexto	+= '1=RPO Mais RECENTE'
				EndIf
				cTexto	+= CRLF

				//PRECISEI FAZER A COMPARAÇÃO USANDO OS SEGUNDOS PORQUE MUITOS ARQUIVOS OCORRE 
				// UMA DIFERENÇA DE 1 SEGUNDO MESMO SENDO O MESMO ARQUIVO!

				If .Not. oFile:Write(cTexto)
					FwAlertError('ERRO ao gravar arquivo de destino.'+CRLF+;
								'Arquivo: '+AllTrim(oFile:cFileName)+CRLF+;
								'Erro: '+oFile:Error():Message,_MsgLinha_)
					lOK	:= .F.
					Exit
				EndIf
			Next
		EndIf
	EndIf

	//Libera memória!------------------------------------------------------------------------------
	If ValType(oFile) == 'O'
		oFile:Close()
	EndIf
	FreeObj(oFile)

	FWFreeArray(ajFontes)
	FWFreeArray(aArquivos)

	FWFreeArray(aRPOSrc)
	FWFreeArray(aType)
	FWFreeArray(aFile)
	FWFreeArray(aLine)
	FWFreeArray(aDate)
	FWFreeArray(aTime)

Return lOK

/*=================================================================================================
Autor      : Cirilo Rocha
Data       : 21/04/2023 
Info       : Rotina para gerar uma listagem dos arquivos de um diretório do servidor, de forma
				recursiva
*================================================================================================*/
Static Function sfGetArqDir(cDir		AS Character;	//01 cDir
						,	aArquivos	AS Array	;	//02 @aArquivos
						)							AS Logical

	//Declaracao de variaveis----------------------------------------------------------------------
	Local aListaArq	:= {}			AS Array
	Local nX						AS Numeric

	//Parametros da rotina-------------------------------------------------------------------------
	ParamType 0		VAR cDir		AS Character
	Default aArquivos	:= {}

	//---------------------------------------------------------------------------------------------
	If Right(cDir,1) <> '\'
		cDir	+= '\'
	EndIf
	aListaArq	:= Directory(cDir+'*.*','HSD',/*uParam1*/,.F.,/*nTypeOrder*/)
	
	If Len(aListaArq) >= (10000-1)	//10k arquivos!!!!
		FwAlertYesNo(	'PROBLEMA: A listagem de arquivos do diretório: '+cDir+' ultrapassa o limite '+;
						' de 10k arquivos.'+CRLF+CRLF+;
						'PROSSEGUE MESMO ASSIM ?',_MsgLinha_)
		FwFreeArray(aListaArq)
		Return .F.
	EndIf

	For nX := 1 to Len(aListaArq)
		If 	aListaArq[nX][cDR_NOME] == '.' .Or. ;
			aListaArq[nX][cDR_NOME] == '..'
			Loop
		EndIf
		If 'D' $ aListaArq[nX][cDR_TIPO] //Sub-Diretório! PRECISA SER ASSIM
			If .Not. sfGetArqDir(cDir+aListaArq[nX][cDR_NOME]	;
								,@aArquivos						;
								)
				FwFreeArray(aListaArq)
				Return .F.
			EndIf
		Else
			aAdd(aArquivos,aClone(aListaArq[nX]))
			aTail(aArquivos)[cDR_NOME]	:= cDir+aTail(aArquivos)[cDR_NOME]
		EndIf
	Next
	FwFreeArray(aListaArq)

Return .T.




//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfGetJsonFonte
@description	Retorna o objeto json do fonte a ser listado
@autor			Cirilo Rocha
@since			30/09/2026
-------------------------------------------------------------------------------------------------*/
Static Function sfGetJsonFonte()

	//-- Declaração de Variáveis ----------------------------------------------
	Local jFonte	:= JsonObject():new()			AS Json

	//-- MANTER ATRIBUTOS EM MAIÚSCULAS --------------------------------------
	jFonte:_addAtributo('PROGRAMA')	:= NIL
	jFonte:_addAtributo('PRJNOME')	:= NIL
	jFonte:_addAtributo('PRJDATA')	:= NIL
	jFonte:_addAtributo('PRJHORA')	:= NIL
	jFonte:_addAtributo('RPONOME')	:= NIL
	jFonte:_addAtributo('RPODATA')	:= NIL
	jFonte:_addAtributo('RPOHORA')	:= NIL

Return jFonte

