#INCLUDE 'RWMake.ch'
#INCLUDE 'Totvs.ch'
#INCLUDE 'ParmType.ch'
#INCLUDE 'CXInclude.ch'

//#############################################################################
//##+----------+----------+-------+-----------------------+------+----------+##
//##|Funcao	   | CXMod11  | Autor | Cirilo Rocha          | Data | 21/01/15 |##
//##+----------+----------+-------+-----------------------+------+----------+##
//##|Descr.    | Cálculo do DV modulo 11                                    |##
//##+----------+-----------+------------------------------------------------+##
//##|   DATA   |Programador| Manutenção efetuada                            |##
//##+----------+-----------+------------------------------------------------+##
//##| 01/03/23 | Cirilo R. | Pequena revisão no fonte                       |##
//##| 18/05/26 | Cirilo R. | Melhoria para tratar Alfanumérico              |##
//##|          |           |                                                |##
//##+----------+-----------+------------------------------------------------+##
//#############################################################################
//-----------------------------------------------------------------------------------//
// Funcionamento do ultimo parametro lDif11 e o Resto10 e Resto11                    //
//  - Se lDif11 significa que o resto da divisao sera subtraido de 11, ou seja       //
//    Resto 9 => Digito => 11-9 => 2                                                 //
//    Isso gera duas possibilidades extras, quando o resto e' 0 ou 1, gera um digito //
//    digito 11 e 10, respectivamente, geralmente na documentacao eles se referem    //
//    como resto 0 ou 1, o que e' a mesma coisa aqui.                                //
//  - Se nao houver subtracao, entao o resto 11 nunca vai existir, e havera apenas   //
//    o resto 10 que precisara ser tratado                                           //
//-----------------------------------------------------------------------------------//
User Function CXMod11(	cCodigo		; //01 
					,	nPesoIni	; //02 Peso Inicio (esquerda <- direita) (def 2)
					,	nPesoFim	; //03 Peso Final (esquerda <- direita) (def 9)
					,	cResto10	; //04 Resto 10, Se lDif11 entao entenda resto 1 (def 1)
					,	cResto11	; //05 Resto 11 (nao existe se !lDif11), Se lDif1l entao entenda resto 0 (def 1)
					,	cRestoZero	; //06 Resto  0, So existe se nao lDif11 resto 11 (def 0)
					,	lDif11		; //07 Se deve ou nao subtrair o resto da divisao por 11 (def .T.)
					)								AS Character
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local cDigito									AS Character
	Local nPeso										AS Numeric
	Local nResto									AS Numeric
	Local nSoma		:= 0							AS Numeric
	Local nJ										AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamObg 0		VAR cCodigo
	Default nPesoIni	:= 2
	Default nPesoFim	:= 9
	Default cResto10	:= '1'
	Default cResto11	:= '1'
	Default cRestoZero	:= '0'
	Default lDif11		:= .T.

	//-------------------------------------------------------------------------
	nPeso	:= nPesoIni
	For nJ := Len(cCodigo) To 1 Step -1
		//-- O Asc() retorna o valor da tabela ASCII, subtraindo por 48, converte o caracter para 
		//	número, feito assim para tratar os novos campoas alfanumericos
		nSoma  += ( Asc( SubStr(cCodigo,nJ,1) ) - 48 ) *nPeso
		
		Do Case
			Case nPeso == nPesoFim		; nPeso := nPesoIni
			Case nPesoFim > nPesoIni	; nPeso ++
			Otherwise					; nPeso --
		EndCase
	Next nJ

	nResto	:=	( nSoma % 11 )
	If lDif11	;	nResto	:= ( 11 - nResto )		;	EndIf

	Do Case
		Case nResto == 0	; cDigito	:=	cRestoZero
		Case nResto == 10	; cDigito	:=	cResto10
		Case nResto == 11	; cDigito	:=	cResto11
		Otherwise			; cDigito	:=	Str(nResto,1)
	EndCase

Return(cDigito)
