#INCLUDE 'RWMake.ch'
#INCLUDE 'Totvs.ch'
#INCLUDE 'ParmType.ch'
#INCLUDE 'Tlpp-Core.th'
#INCLUDE 'CXInclude.ch'

//#############################################################################
//##+==========+===========+=======+===================+======+=============+##
//##|Programa  | CXParForm | Autor | Cirilo Rocha      | Data | 25/11/2022  |##
//##+==========+===========+=======+===================+======+=============+##
//##|Desc.     | Função para expressar de forma mais clara os parâmetros    |##
//##|          |  formais das funções internas padrões                      |##
//##+==========+==========+=================================================+##
//##| DATA     | ANALISTA | MANUTENÇÃO EFETUADA                             |##
//##+==========+==========+=================================================+##
//##|2024/03/27| Cirilo R | Adicionado tipo Json                            |##
//##|2026/03/01| Cirilo R | Pequena revisão no fonte                        |##
//##|          |          |                                                 |##
//##+==========+==========+=================================================+##
//#############################################################################
User Function CXParForm(cParam	AS Character);	//01 cParam
													AS Character

	//Declaracao de variaveis----------------------------------------------------------------------
	Local cTipo										AS Character
	Local cObrig									AS Character
	Local cRet	:= ''								AS Character
	Local nX										AS Numeric

	//Parametros da rotina-------------------------------------------------------------------------
	ParamObg 0		VAR cParam

	//---------------------------------------------------------------------------------------------
	For nX := 1 to len(cParam) step 2
		cTipo	:= SubStr(cParam,nX,1)
		cObrig  := SubStr(cParam,nX+1,1)
		Do Case
			Case cTipo == 'C'	;	cTipo	:= 'Char'
			Case cTipo == 'A'	;	cTipo	:= 'Arr'
			Case cTipo == 'N'	;	cTipo	:= 'Num'
			Case cTipo == 'F'	;	cTipo	:= 'Float'
			Case cTipo == 'D'	;	cTipo	:= 'Data'
			Case cTipo == 'L'	;	cTipo	:= 'Log'
			Case cTipo == 'B'	;	cTipo	:= 'Bloc'
			Case cTipo == 'O'	;	cTipo	:= 'Obj'
			Case cTipo == 'J'	;	cTipo	:= 'Json'
			Case cTipo == '*'	;	cTipo	:= 'Var'
			Otherwise			;	cTipo	+= ' - '+'Desconhecido'
		EndCase
		Do Case
			Case cObrig == 'R' 	;	cTipo	:= '<'+cTipo+'>'		//-- Obrigatório
			Case cObrig == 'O' 	;	cTipo	:= '['+cTipo+']'		//-- Opcional
			Otherwise			;	cTipo	:= cTipo+'[des]'
		EndCase

		cRet	:= U_CXConcTxt(cRet,cTipo,',')
	Next

Return cRet
