#INCLUDE "RWMake.ch"
#INCLUDE "Protheus.ch"
#INCLUDE "Totvs.ch"
#Include "ParmType.ch"
#Include "CXInclude.ch"

//#############################################################################
//##+==========+==========+=======+====================+======+=============+##
//##|Programa  | CXPutCpo | Autor | Cirilo Rocha       | Data | 29/05/2018  |##
//##+==========+==========+=======+====================+======+=============+##
//##|Descricao | Funcao generica para preencher campos ou variaveis de memo-|##
//##|          | ria de acordo com os parametros passados.                  |##
//##|          |                                                            |##
//##|          | USAR APENAS NOS CASOS EM QUE SE TEM CERTEZA QUE O VALOR    |##
//##|          | PODE SER ATRIBUIDO SEM NENHUMA VALIDACAO/CONTROLE!!!!!!!   |##
//##+==========+===============+============================================+##
//##|   DATA   | Programador   | Manutencao efetuada                        |##
//##+==========+===============+============================================+##
//##| 03/09/19 | Cirilo Rocha  | Pequena revisao no fonte                   |##
//##| 11/05/26 | Cirilo Rocha  | Correção no CXFieldPut                     |##
//##|          |               |                                            |##
//##+==========+===============+============================================+##
//#############################################################################
User Function CXPutCpo(	cCampo			AS Character; //01 Campo a ser preenchido
					,	lMem			AS Logical	; //02 Preenche campo na memoria
					,	cAlias			AS Character; //03 Alias da tabela ou M-> se memoria
					,	lGrid			AS Logical	; //04 Se memoria em Grid (def busca o aCols/aHeader se memoria)
					,	xValor			AS Variant	; //05 Valor a ser preenchido
					,	nLine			AS Numeric	; //06 Linha do aCols que esta sendo manipulada (def N)
					,	aHeaderPastPar	AS Array	; //07 aHeader onde serao salvos os dados (def aHeader)
					,	aColsPastPar 	AS Array	; //08 aCols onde serao salvos os dados (def aCols)
					,	cIdForm 		AS Character; //09 Id do formulario do MVC (def faz uma busca)
					,	lGatilho		AS Logical	; //10 Se a execucao veio de um gatilho (def .F.)
						)

	//-- Declaração de Variáveis ----------------------------------------------
	Local aTemp		AS Array
	Local aModelos	AS Array
	Local xRet		AS Variant
	Local nX		AS Numeric
	Local lTemGrid	AS Logical
	Local oModel 	AS Object
	Local lMVC		AS Logical

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamObg 0		VAR cCampo
	Default cAlias := FwTabPref(cCampo)
	ParamType 4		VAR xValor					AS Character,Numeric,Date,Logical
	Default  lGatilho := .F.

	//-- Inicializa Variáveis -------------------------------------------------
	oModel 	:= fwModelActive()
	lMVC	:= ( ValType(oModel) == 'O' .And. oModel:IsActive() ) .Or. ValType(cIdForm) == 'C'	//preciso tambem verificar se o oModel esta realmente ativo!!!

	//-- Pre-Processamento
	cCampo	:= AllTrim(cCampo)
	cCampo	:= StrTran(cCampo,'M->')
	cCampo	:= Left(cCampo,10)

	//-- Variáveis compartilhadas de mensagens de erro
	cMsgErr	:= IIf(Type('cMsgErr')<>'C','',cMsgErr)
	cCodErr	:= IIf(Type('cCodErr')<>'C','',cCodErr)
	cSoluc	:= IIf(Type('cSoluc')<>'C','',cSoluc)
	cMsg	:= IIf(Type('cMsg')<>'C','',cMsg)

	If 	ValType(nLine)	== 'U' .And. ;
		Type('n') == 'N'

		nLine	:= n
	EndIf

	//-- Ajusta o tamanho do campo por compatibilidade com o MVC
	If ValType(xValor) == 'C'
		aTemp	:= FwTamSX3(cCampo)
		
		If 	aTemp == NIL .Or. ;
			Len(aTemp) < 3
			
			cCodErr	:= U_CXTxtMsg(,,.T.)
			cMsgErr	:= 'ERRO: Não foi possível localizar o campo '+cCampo+' no SX3'
			cSoluc	:= 'INFORME O SETOR DE T.I.'
			cMsg	:= cCodErr+': '+cMsgErr+IIf(!Empty(cSoluc),CRLF+'SOLUÇÃO: '+cSoluc,'')
			U_CXHelp(cCodErr,,cMsgErr,,cSoluc)
			
		ElseIf aTemp[3] == 'C'	//Precisa ser assim para tratar os campos MEMO
			xValor	:= PadR(xValor,aTemp[1])
		EndIf
	EndIf

	If lMVC	//-------------------------------------------------------------------------------------

		//Busca o campo nos formularios MVC (controle de erros)
		If Empty(cIdForm)
			aModelos	:= oModel:getAllSubModels()	//-- Retorna todos os submodelos
		Else
			aModelos	:= {oModel:GetModel(cIdForm)}
		EndIf
		
		If ValType(aModelos[1]) == 'O'
			For nX := 1 to len(aModelos)
				If aModelos[nX]:HasField(cCampo)
					cIdForm	:= aModelos[nX]:GetId()
					Exit
				EndIf
			Next
		EndIf

		//Controle de erros
		If 	Empty(cIdForm)

			cCodErr	:= U_CXTxtMsg(,,.T.)
			cMsgErr	:= 'ERRO: Não foi possível localizar o campo '+cCampo+' no objeto MVC ativo.'
			cSoluc	:= 'INFORME O SETOR DE T.I.'
			cMsg	:= cCodErr+': '+cMsgErr+IIf(!Empty(cSoluc),CRLF+'SOLUÇÃO: '+cSoluc,'')
			U_CXHelp(cCodErr,,cMsgErr,,cSoluc)

			Return NIL
		EndIf

		xRet	:= FWFldPut(cCampo	;	//01
						,	xValor	;	//02
						,	nLine	;	//03
						,	oModel	;	//04
						,	.F.		;	//05
						,	.T.		;	//06 Forca o preenchimento campo (CUIDADO!!!)
							)

	ElseIf 	lMem .Or. ;	//-------------------------------------------------------------------------
			cAlias == 'M->'

		If 	aHeaderPastPar == NIL .And. ;
			Type('aHeader') == 'A'

			aHeaderPastPar	:= @aHeader
		EndIf

		If 	aColsPastPar == NIL .And. ;
			Type('aCols') == 'A'

			aColsPastPar	:= @aCols
		EndIf

		lTemGrid	:= 	ValType(aColsPastPar) == 'A' .And. ;
						ValType(aHeaderPastPar) == 'A' .And. ;
						GdFieldPos(cCampo,aHeaderPastPar) > 0

		//Tratamento Default para lGrid
		If ValType(lGrid) == 'U'		//Se nao informou se era grid, busca no aCols
			lGrid	:= 	lTemGrid
		ElseIf lGrid		//Se informou que era grid verifica se existe aCols
			If !lTemGrid
			
				cCodErr	:= U_CXTxtMsg(,,.T.)
				cMsgErr	:= 'ERRO: Não foi possível localizar o aCols e aHeader para com o campo '+cCampo
				cSoluc	:= 'INFORME O SETOR DE T.I.'
				cMsg	:= cCodErr+': '+cMsgErr+IIf(!Empty(cSoluc),CRLF+'SOLUÇÃO: '+cSoluc,'')
				U_CXHelp(cCodErr,,cMsgErr,,cSoluc)

				Return NIL
			EndIf
		EndIf

		If lGrid
			xRet	:= GdFieldPut(	cCampo			;	//01
								,	xValor			;	//02
								,	nLine			;	//03
								,	aHeaderPastPar	;	//04
								,	aColsPastPar	;	//05
								)

			If Type('M->'+cCampo) <> 'U'
				&('M->'+cCampo)	:= xValor
			EndIf
		Else
			&('M->'+cCampo)	:= xValor
		EndIf

	Else	//-------------------------------------------------------------------------------------
		xRet	:= U_CxFieldPut(cCampo	;	//01
							,	xValor	;	//02
							,	cAlias	;	//03
								)
	EndIf
	
	//-- Quando é gatilho retorno o próprio conteudo
	If lGatilho	;	xRet	:= xValor		;	EndIf

Return xRet
